### ISSUE TITLE
The extension is missing on Chrome Web store

### ISSUE THREAD

**Issue by lsvy97** [dessant/web-archives#105]
The extension is removed from Chrome Web store

https://chromewebstore.google.com/detail/web-archives/hkligngkgcpcolhcnkgccglchdafcnao

![image](https://github.com/user-attachments/assets/00f0ab0a-96c2-474d-9ef8-265ddefdff15)

**Comment by j9d3it** [comment]
I just checked and that link is working fine for me.

**Comment by lsvy97** [comment]
Can confirm, Extesion is back in store again. Closing the issue.

![image](https://github.com/user-attachments/assets/6b8f4b9a-a9a6-43a3-816c-337ae1e43840)
