### ISSUE TITLE
Problems with Yandex engine

### ISSUE THREAD

**Issue by n0samu** [dessant/web-archives#106]
**System**

* OS: Windows 10
* Browsers: Firefox 132, Chromium 131
* Extension version: 7.0.0

**Bug description**

When I select the Yandex engine, I experience a few problems that make it very difficult to use:
- Even if an exact URL match is found, the extension still retries the search without the `url:` operator. Worse, if I manually retype the `url:` operator into the Yandex search bar and hit Enter, the extension redirects me back to the search without the `url:` operator. I'm guessing this problem was caused by a Yandex site design change that broke the extension's detection of search results.
- The extension's automated clicks and pasting often trigger Yandex's CAPTCHA, so the automation ends up costing more time than it saves.

I'd propose simplifying the Yandex engine to simply open `https://yandex.com/search/?text=url%3A{url}`. This seems to work well and run less risk of triggering CAPTCHAs. I don't understand why the extension opens the Yandex homepage and pastes in the search term instead of opening the search results page directly.

**Comment by dessant** [comment]
CSS selectors were no longer matching, the fix will be released with the next update.

The extension searches using the input field to lower the occurrence of CAPTCHAs, the method you suggest has lead to repeated challenges within the same session in the past. Right now a challenge may occur at the start of a session when there are no preexisting cookies saved by Yandex, and there's not much the extension can reasonably do about it.

**Comment by n0samu** [comment]
Alright, thanks! 👍
