### ISSUE TITLE
Arweave archived pages

### ISSUE THREAD

**Issue by jugi1** [dessant/web-archives#16]
Can you please add Arweave archived pages.
It is blockchain based permaweb project 
https://www.arweave.org/archiving.html

**Comment by dessant** [comment]
Is the a way to publicly search and view archived pages, without signing up for a wallet and spending tokens?

**Comment by jugi1** [comment]
> Is there a way to publicly search and view archived pages, without signing up for a wallet and spending tokens?

Anyone can search archived pages for free.
1.
https://773qilr4hrro.arweave.net/rvoldM5Y9LbQ46vLs29IAHfdv3ptqZb67g8xXRVeiDc
2.
https://mdflqndwudrx.arweave.net/A7ctf1azriZxHGWKurMQfDFrGOncG-MBn4A59Tt1kzw/index.html#/transactions

You can also get 1 AR token for free  to archive when you sign up with Google:
https://tokens.arweave.org/#/wallet

For more details best talk with AR dev team.
Thanks

**Comment by dessant** [comment]
I don't have time to spend trying to figure out if this thing has a public web API that is searchable by page URL, the links you shared are just the latest transaction logs.

You're probably already using Arweave, so if you want to have it in this extension, please find the relevant details, and I'll reconsider the feature request.
