### ISSUE TITLE
Redirect Google+ and others automatically to preferred supplier

### ISSUE THREAD

**Issue by jtagcat** [dessant/web-archives#18]
**Is your feature request related to a problem? Please describe.**
Google+ is dead
**Describe the solution you'd like**
Let you define a regex to provider, say
Regex `plus.google.com/.*/posts/.*` or `something-other.dead` Provider `Wayback Machine` and `Archive.is`.

Why not just redirect g+ to archive.org? To allow expansion as other things go down.

**Comment by dessant** [comment]
I think this is a great idea, but it's out of scope for this project. You could create a separate extension that automatically redirects dead pages to an archive source and make it configurable, I recall seeing a similar extension, but I couldn't find it now to share it.
