### ISSUE TITLE
Load archive.today instead of archive.is

### ISSUE THREAD

**Issue by gloschtla** [dessant/web-archives#19]
Mostly archive.is is overloaded. If you load archive.today instead, it will be forwarding to the quickest [alias domain](https://www.archiveteam.org/index.php?title=Archive.today#Aliases). 
archive.is archive.li archive.vn archive.fo archive.md archive.ph

**Comment by dessant** [comment]
I've been in contact with the maintainer of Archive.is, and they have never suggested to use `archive.today` because of performance issues with `archive.is`. I'll reconsider this feature request if the maintainer will advise against linking to `archive.is`.

**Comment by gloschtla** [comment]
What if archive.is is down? would it not be useful to be forwarded to another alias?

**Comment by BrandonKMLee** [comment]
archive.md archive.fo and archive.ph are also proper gateways.

**Comment by dessant** [comment]
In Web Archives 7.2.0 you'll be able to change your preferred host for Wayback Machine and Archive.is from the extension's options.
