### ISSUE TITLE
Automatically strip query string for pages that aren't found

### ISSUE THREAD

**Issue by huyz** [dessant/web-archives#22]
**Is your feature request related to a problem? Please describe.**
Sometimes a URL isn't found in archive.is because of a superfuous query string

**Describe the solution you'd like**
If there is no match inside of archive.is, then automatically strip the query string and try again.
Or maybe just strip the query string before searching archive.is

**Describe alternatives you've considered**
I edit the URL manually and try again.

**Additional context**
Here's an example URL: https://www.economist.com/united-states/2020/06/11/meet-our-us-2020-election-forecasting-model?cid1=cust/ednew/n/bl/n/2020/06/11n/owned/n/n/nwl/n/n/NA/494260/n

**Comment by dessant** [comment]
Thanks for the feature request, this issue also applies to the Wayback Machine.

On archive.is we could redirect to `https://archive.is/https://www.economist.com/united-states/2020/06/11/meet-our-us-2020-election-forecasting-model*` when no results are found. Note the asterisk at the end, that will also catch snapshots with different query strings.

**Comment by dessant** [comment]
On Wayback Machine we can also redirect to a similar URL that catches pages archived with different query strings: https://web.archive.org/web/*/https://www.economist.com/united-states/2020/06/11/meet-our-us-2020-election-forecasting-model*

**Comment by mollyrealized** [comment]
Bumping up and seconding this request; getting negative answers from the respective archives thanks to the appended tracking string.

**Comment by githubcopyrightdoctor** [comment]
> **Is your feature request related to a problem? Please describe.**
> Sometimes a URL isn't found in archive.is because of a superfuous query string
> 
> **Describe the solution you'd like**
> If there is no match inside of archive.is, then automatically strip the query string and try again.
> Or maybe just strip the query string before searching archive.is
> 
> **Describe alternatives you've considered**
> I edit the URL manually and try again.
> 
> **Additional context**
> Here's an example URL: https://www.economist.com/united-states/2020/06/11/meet-our-us-2020-election-forecasting-model?cid1=cust/ednew/n/bl/n/2020/06/11n/owned/n/n/nwl/n/n/NA/494260/n

**![CamScanner ٠٧-١٢-٢٠٢٣ ١٢.٣١.jpg](https://github.com/dessant/web-archives/assets/112034987/a0966de1-de62-4958-9d07-175e3e064808)

**

**Comment by dessant** [comment]
Let's track this issue in https://github.com/dessant/web-archives/issues/76.
