### ISSUE TITLE
Link to oldest version of a webpage in Wayback Machine

### ISSUE THREAD

**Issue by wodim** [dessant/web-archives#25]
The way the current Wayback Machine link works is it retrieves the latest archived version of the site. I think it would be nice to also add a link to the oldest (first) archived version of a site. This can be achieved by following this link:

https://web.archive.org/web/0/[URL]

For example

https://web.archive.org/web/0/http://github.com/

**Comment by wodim** [comment]
Example where this would be useful

https://web.archive.org/web/http://groups.google.com/groups?selm=1165244925.433286.14150@16g2000cwy.googlegroups.com (redirects to nothingness)

https://web.archive.org/web/0/http://groups.google.com/groups?selm=1165244925.433286.14150@16g2000cwy.googlegroups.com (redirects to something)

**Comment by dessant** [comment]
We'll be able to customize search engines in the future, so you can have multiple instances of the same search engine, configured for different use cases. Let's track this at https://github.com/dessant/web-archives/issues/37.
