### ISSUE TITLE
context menu missing on Android firefox

### ISSUE THREAD

**Issue by clach04** [dessant/web-archives#30]
**System**

* OS name: andriod
* OS version: 10
* Browser name:  Firefox
* Browser version: 88.1.3 (Build #2015808507)
* Extension version: 2.1.0

**Firefox missing feature**
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1595822

**Comment by dessant** [comment]
The upstream bug report is already documented in the AMO description, there is nothing we can do here.

**Comment by clach04** [comment]
Work around does not work with nightly Firefox 90.0a1 (Build #2015809227). Settings come up but UI does not. Seems like another Firefox deficiency/bug
