### ISSUE TITLE
404 on Google

### ISSUE THREAD

**Issue by yaakovfeldman** [dessant/web-archives#33]
I'm a big fan of the extension and I use it on Android Firefox Nightly. It used to work perfectly but for several months for every page I try, I get a 404 when I choose the Google option. Other options (eg wayback machine) work fine. For example, the image below shows the result of attempting to view the cached version of this GitHub project.

![Screenshot_20210820-094611_Firefox Nightly](https://user-images.githubusercontent.com/17687145/130207493-12f5a0f6-f412-4240-815a-cfc1f8ab09f5.png)

My version is 2.1.0 from the Firefox store.

**Comment by dessant** [comment]
Thanks for the bug report! It seems Google has begun to break the cache viewer for Firefox users on Android. They've been doing the same with Google Search for years now, when you visit Google from Firefox for Android, you are served an outdated search page. The workaround is to change the user agent to Chrome or to any other browser based on Chromium.

The link below loads correctly from mostly all mobile browsers, except Firefox for Android.

https://webcache.googleusercontent.com/search?q=cache:https%3A%2F%2Fgithub.com%2Fdessant%2Fweb-archives

**Comment by yaakovfeldman** [comment]
Thank you! I used a user agent switcher and it works perfectly again.

**Comment by dessant** [comment]
Let's keep this open, I plan to implement the workaround in Web Archives too.

**Comment by dessant** [comment]
Fixed in https://github.com/dessant/web-archives/commit/d7cd2ef9e7c6717df4ffc708ae15f2b2fe207737.
