### ISSUE TITLE
Add options to unarchive

### ISSUE THREAD

**Issue by 35609902357** [dessant/web-archives#34]
Add options to view the current page (via the extension button) or links (via context menu) in the actual website.
The reason for this is when surfing an archived page (with `archive.org` or `archive.is` for example) all links turn to archived versions. Many of them are not actually archived though, or the user might decide to view the current version of them.

**Comment by dessant** [comment]
This is a great idea! I've also had to manually edit the URL several times before to get to the current version, I'm sure people will find the feature useful.

**Comment by dessant** [comment]
In Web Archives 3.1.0 you can open the current page from the toolbar popup and the context menu while browsing an archived or cached page.

![screenshot](https://user-images.githubusercontent.com/7513068/149623007-30c0b64f-324d-49ad-8fa9-41dfe922a40a.png)

**Comment by 35609902357** [comment]
> In Web Archives 3.1.0 you can open the current page from the toolbar popup and the context menu while browsing an archived or cached page.

Can this feature be made to work on links inside the archived page? Links in archived pages (e.g. in archive.org) point to archived versions of the linked resource. Right-clicking a link would allow to open the actual link unarchived in a new tab via context menu, without loading the archived page first.

**Comment by dessant** [comment]
That's how it works right now, the "Open current page" content menu item appears only when it's relevant, and it behaves differently depending on the context: it will act on the link URL if you right-click on a link, and use the tab URL when you right-click at other parts of a page. Make sure to set the context menu visibility to "Show" in the extension's options if you also want to use the extension in the context of the page, otherwise it will only appear when you right-click on a link.

**Comment by 35609902357** [comment]
Great work! It's really nice. I think there's a small bug because if context menu is set to "Show" then "Open current page" appears twice. Maybe you wanted to move one of those in the main menu and leave the other in the submenu?

**Comment by dessant** [comment]
An extension can only add a single top-level item to the context menu. I can't reproduce the bug with the duplicate menu items in the submenu, what browser are you using? Does the issue persist after a browser restart?

**Comment by 35609902357** [comment]
The bug is in the Tor Browser, which is Firefox ESR, but the bug is not present in regular Firefox ESR. I confirm the double menu item appears only when "Show" is selected. If "Show for links" is selected there's only one "Open current page".

**Comment by grahamperrin** [comment]
> … from the toolbar popup and the context menu while browsing an archived or cached page. …

EXCELLENT!

**Comment by dessant** [comment]
@35609902357, I can't reproduce the issue in Tor Browser 11.0.4 (based on Mozilla Firefox 91.5.0esr) either. You may have found a browser bug, please let me know if you find a way to reproduce the issue with a fresh profile.

**Comment by 35609902357** [comment]
The bug is present in the Wayback machine only. On Archive.is for example it's not.
