### ISSUE TITLE
Add to context menu when on the "New Tab" (blank tab)

### ISSUE THREAD

**Issue by crass** [dessant/web-archives#39]
**Is your feature request related to a problem? Please describe.**

When opening a new tab, no url is loaded yet, but there links like "Recommended by Pocket", that I would like to search for on the Wayback machine without loading the link.

**Describe the solution you'd like**

Right-click on a pocket link, go to the "Web Archives" submenu, and select "Wayback Machine". It should be possible because uBlock has a menu item in that context menu.

**Describe alternatives you've considered**

Copy the link manually and put it into the Wayback Machine, which is a small pain.

**Comment by dessant** [comment]
Thanks for the suggestion, I've made a test and the feature should be easy to implement.

**Comment by dessant** [comment]
Fixed in https://github.com/dessant/web-archives/commit/096567a973e74df9ef84268cde8afc47ede82dd2.
