### ISSUE TITLE
Add support for ghostarchive.org

### ISSUE THREAD

**Issue by ak-42** [dessant/web-archives#41]
Hello. Enloying the extension very much. Thank you.

Could you please consider supporting [/ghostarchive.org](https://ghostarchive.org/) as one of the services?
I like using it since it is in my experience the fastest of the archiving services, and it would be great to use it with the convenience of this extension.

Thanks

**Comment by atomGit** [comment]
...plus it works without JS for the most part

**Comment by atomGit** [comment]
thanks for adding ghostarchive - much appreciated :)
