### ISSUE TITLE
De-localise the link to addons.mozilla.org

### ISSUE THREAD

**Issue by grahamperrin** [dessant/web-archives#43]
https://github.com/dessant/web-archives/pull/42/files

**Comment by Gitoffthelawn** [comment]
I beat you too it, and also took care of Opera and Safari links:  :)

https://github.com/dessant/web-archives/pull/38/files

Not sure why pull requests aren't accepted for this project.

**Comment by dessant** [comment]
The extension only supports English, so I'd like to link to the supported locale for now.
