### ISSUE TITLE
Not listed among extensions in Safari preferences. Installed via Appstore

### ISSUE THREAD

**Issue by pajaco** [dessant/web-archives#46]
**System**

* OS name: MacOS 
* OS version: 12.1
* Browser name: Safari
* Browser version: 15.2 (17612.3.6.1.6)
* Extension version: 3.1.0

**Bug description**
I purchased and installed Web Archives for Safari via AppStore. It doesn't show among extensions in Safari preferences.
The button encouraging to "Quit and Open Safari Extensions Preferences..." in the little app that got installed doesn't do anything other than the visual mouse down/up visual cues.

**Comment by dessant** [comment]
Thanks for the purchase! :yum: Your description appears to fit this bug report: https://github.com/dessant/search-by-image/issues/160#issuecomment-1019567365

This is a macOS bug, but there is a workaround: https://github.com/dessant/search-by-image/issues/160#issuecomment-1021936996

Call this command from Terminal and restart your Mac:

```sh
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Safari.app
```

https://github.com/refined-github/refined-github/issues/4216

https://github.com/refined-github/refined-github/issues/4216#issuecomment-817097886

Please let me know if this fixed the issue on your device.

**Comment by pajaco** [comment]
Fantastic! Worked perfectly. Thanks.
