### ISSUE TITLE
Save  the current page to the Internet Archive

### ISSUE THREAD

**Issue by neoOpus** [dessant/web-archives#50]
It would be great to add an icon next to each service to archive the current tab or right-click menu... 

Here is a javascript bookmarklet that will save the current page to the Internet Archive. This opens a new window so you can continue browsing while it's being archived.

javascript:var w=window.open('https://web.archive.org/save/'+location.href,'','scrollbars=1,status=0,resizable=1,location=0,toolbar=0');

![image](https://user-images.githubusercontent.com/1388336/168083274-06599574-68bb-4533-8efd-9c97d19f165e.png)

**Comment by dessant** [comment]
Tracking at https://github.com/dessant/web-archives/issues/10.
