### ISSUE TITLE
Is there a userscript version of this for Grease/Tampermonkey?

### ISSUE THREAD

**Issue by Jaladhjin** [dessant/web-archives#58]
**Is your feature request related to a problem? Please describe.**

Not really no. Just more reliable than Browser Store addons that could get removed at any time.
**Describe the solution you'd like**

a userscript version of this for Grease/Tampermonkey?
**Describe alternatives you've considered**

Installing the Browser plugin
**Additional context**

**Comment by dessant** [comment]
There is no plan to maintain a userscript, mainly because userscripts are too limited to support the feature set of this project.
