### ISSUE TITLE
4.0.0 replaces deprecated engines with unwanted engines

### ISSUE THREAD

**Issue by practik** [dessant/web-archives#64]
**System**
* OS name: macOS
* OS version: 11.7
* Browser name: Firefox
* Browser version: 109
* Extension version: 4.0.0

**Bug description**
Before updating from 3.1.0, my selected search engines included two that are now deprecated, Yahoo Japan and Qihoo 360. After the update, those were gone from my selections, as expected, but now Gigablast and Megalodon (previously unselected) had been added to my selections, which was not expected. Not a big deal, but I thought you should know.

As a side note: The fact that Yahoo Japan blocks EU users seems like a poor reason to remove it. Why take away that functionality for everyone outside the EU?

**Logs**
n/a

**Comment by dessant** [comment]
Those engines were enabled to maintain the same number of default search engines. Last time I had access to Yahoo Japan, it was serving cached content from Google, so it was mostly just an alternative to Google Cache. Since they blocked EU visitors from accessing the site, I can no longer maintain the search engine in Web Archives, and I see no reason to pay for a VPN to develop for a search engine that provides no value to us.

**Comment by practik** [comment]
> Last time I had access to Yahoo Japan, it was serving cached content from Google

Aha, that explains it – makes sense. Thanks!

**Comment by 1989891** [comment]
> > Last time I had access to Yahoo Japan, it was serving cached content from Google
> 
> Aha, that explains it – makes sense. Thanks!

**Comment by 1989891** [comment]
#55

**Comment by 1989891** [comment]
> > Last time I had access to Yahoo Japan, it was serving cached content from Google
> 
> Aha, that explains it – makes sense. Thanks!

**Comment by 1989891** [comment]
#

> **System**
> 
>     * OS name: macOS
> 
>     * OS version: 11.7
> 
>     * Browser name: Firefox
> 
>     * Browser version: 109
> 
>     * Extension version: 4.0.0
> 
> 
> **Bug description** Before updating from 3.1.0, my selected search engines included two that are now deprecated, Yahoo Japan and Qihoo 360. After the update, those were gone from my selections, as expected, but now Gigablast and Megalodon (previously unselected) had been added to my selections, which was not expected. Not a big deal, but I thought you should know.
> 
> As a side note: The fact that Yahoo Japan blocks EU users seems like a poor reason to remove it. Why take away that functionality for everyone outside the EU?
> 
> **Logs** n/a
