### ISSUE TITLE
Download link(s)? 

### ISSUE THREAD

**Issue by YesTrustMe** [dessant/web-archives#66]
This extension appeared as an option for Firefox on Android but no link to download the extension was seen.

**Comment by dessant** [comment]
I'm not sure what you're talking about, you'll have to be more specific. The extension can be installed from Menu > Add-ons in Firefox for Android, there is a + button next to each extension in that list.

**Comment by YesTrustMe** [comment]
I see no option to download the extension. No DOWNLOAD button or anything where I can download it. Hopefully, this clears things up. Thanks.

**Comment by dessant** [comment]
Something must be wrong with your browser, you could try asking for support on the Firefox subreddit.
