### ISSUE TITLE
Allow changing "archive.is" url

### ISSUE THREAD

**Issue by soredake** [dessant/web-archives#71]
**Is your feature request related to a problem? Please describe.**
Most of the "archive.is" service mirror's don't work with cloudflare dns which i use, only "archive.md" mirror works (mostly)

**Describe the solution you'd like**
Having a way to specify "archive" service url

**Describe alternatives you've considered**

**Additional context**

**Comment by dessant** [comment]
Let's track this issue at https://github.com/dessant/web-archives/issues/37.
