### ISSUE TITLE
"Archive.is" doesn't work anymore

### ISSUE THREAD

**Issue by PhillyMay** [dessant/web-archives#74]
**System**
OS: Android, Windows
OS Version: Android 12, Windows 11 22H2
Browser: Kiwi (Android), Firefox (Android, Windows), MS Edge (Windows)
Browser Version: Kiwi (V.116), Firefox (V.116), MS Edge (V.116)
Extension Version: latest version

**Bug description**
Archive.is is not reachable anymore, neither via the extension nor directly by entering the url. I would suggest to change the default link to archive.ph as this link does work. Or maybe consider [#37](https://github.com/dessant/web-archives/issues/37) in addition with [#71](https://github.com/dessant/web-archives/issues/71) a way for the users to change the urls by themselves.

**Comment by dessant** [comment]
The customization of the archive.is domain can be followed in this issue: https://github.com/dessant/web-archives/issues/37

You're most likely using Cloudflare DNS if you cannot access Archive.is: https://jarv.is/notes/cloudflare-dns-archive-is-blocked/
