### ISSUE TITLE
How to align the image in the plugin to the left or right.

### ISSUE THREAD

**Issue by w316525096** [dessant/web-archives#78]
谢谢作者制作插件，很好用。（这个问题与插件无关，我很喜欢插件里的背景）
https://www.rijksmuseum.nl/ 这个网站里的艺术图片，并不能像插件里展示的图片那样展示，请问是怎么做到的。
插件图片： [link](https://camo.githubusercontent.com/d8ed32b9e2daae56eae9b17b8b09f6c65af7a0e38ef5ee63f17065f05748cb7d/68747470733a2f2f692e696d6775722e636f6d2f51616d7735446d2e706e67)
鼠标在动的模式：[link](https://i.imgur.com/9sQvPmO.png)
鼠标悬停不动的模式：[link](https://i.imgur.com/Bim0YDm.png)
———————— translation ——————————
Thank you to the creator for making this plugin, it’s very useful. (This question is unrelated to the plugin, but I really like the background in the plugin.
How can the art images on the website https://www.rijksmuseum.nl/ not be displayed like the images shown in the plug-in.
The plug-in images：![link](https://camo.githubusercontent.com/d8ed32b9e2daae56eae9b17b8b09f6c65af7a0e38ef5ee63f17065f05748cb7d/68747470733a2f2f692e696d6775722e636f6d2f51616d7735446d2e706e67)
Mouse in motion mode：![link](https://i.imgur.com/9sQvPmO.png)
Mouse in idle mode：![link](https://i.imgur.com/Bim0YDm.png)

**Comment by dessant** [comment]
The product images are composites, they were edited. The main subjects of the background images were all taken from Rijksmuseum, that's why the museum's website was chosen to be displayed in the address bar.

**Comment by w316525096** [comment]
Thank you for your reply, I like this website.

**Comment by dessant** [comment]
It really is fascinating, and a great source of inspiration.
