### ISSUE TITLE
Please add support for perma.cc

### ISSUE THREAD

**Issue by dimasahmad** [dessant/web-archives#8]
[Perma.cc](https://perma.cc/) is a Harvard’s Library Innovation Lab project used mainly by academic and law entities. They have around one million pages archived. They have an [API](https://perma.cc/docs/developer#developer-public-archives) too.

**Comment by dessant** [comment]
I've only skimmed the public API docs, but there does not seem to be a way to search by URL.

https://perma.cc/docs/developer#get-all-public-archives

**Comment by dessant** [comment]
I'd be happy to add the service if they support searching by URL without signing up, let me know if you find a way.

**Comment by dessant** [comment]
I have found a way to search their archive by URL, though the API does not seem to be documented.

https://api.perma.cc/v1/public/archives/?format=json&url=https%3A%2F%2Fnews.ycombinator.com
