### ISSUE TITLE
Extension for iOS and iPasOS

### ISSUE THREAD

**Issue by rtmlp** [dessant/web-archives#86]
Hi,

I have purchased this extension recently. Thanks a lot for making this extension available for Mac devices. Just want to check if there is any plan to make it available or develop it for iOS as well as iPadOS as well. 

Thanks

**Comment by dessant** [comment]
Hi, thanks for supporting the project! I've been planning to release the extension for iOS, and the current version already runs on an iPhone.

The main limitation is that the web extension API in Safari does not allow targeting a specific tab for changing the user agent, we can filter only by the request URL. A couple of search engines require a desktop user agent, such as Bing, Yandex and Yahoo, so we'll have to settle with changing the user agent for the specific search URL, which could match an unrelated tab and also change its user agent.

In any case I'd love to sort out this issue in the next 2 months and release the extension on the App Store. I'll share a link here when the app is ready for mobile devices, you should be able to download it as part of your existing purchase.

**Comment by rtmlp** [comment]
Thanks a lot for the detailed information on the iPhone development

**Comment by jmatthiass** [comment]
Hey! I also just purchased on macOS and love the extension.
I'm hoping you're still considering launching a universal app for iOS. ✌️
