### ISSUE TITLE
strip UTM parameters from URL before searching

### ISSUE THREAD

**Issue by hauntingEcho** [dessant/web-archives#89]
**System**

* OS name: Debian
* OS version: 12
* Browser name: Firefox
* Browser version: 121.0 (64-bit)
* Extension version: 5.0.0

**Bug description**

Searching several of the services with a `utm_source` query parameter can cause false negatives, while the page is found when the parameter is removed. Stripping [UTM parameters](https://en.wikipedia.org/wiki/UTM_parameters) from URLs before checking archives will give more accurate results.

**Comment by mollyrealized** [comment]
This is issue #76.  I'm not sure if this project has anyone working on it, though.

**Comment by hauntingEcho** [comment]
yup - closing my duplicate.
