### ISSUE TITLE
Google Cache has been shut down

### ISSUE THREAD

**Issue by dessant** [dessant/web-archives#90]
Google will no longer cache web pages, they have removed the feature from Google Search. This is an ongoing trend among search engines that has started two years ago with search engines from China removing access to cached versions of web pages.

Already cached pages can still be accessed, and Web Archives should continue working until Google completely shuts down the service.

https://arstechnica.com/gadgets/2024/02/google-search-kills-off-cached-webpages/

**Comment by mollyrealized** [comment]
Apparently, it has now officially killed them off today.

**Comment by dessant** [comment]
Cached pages still load here. Let's use the link below for testing, we can remove Google Cache from the extension when the cached Wikipedia page stops being served.

https://webcache.googleusercontent.com/search?q=cache:https%3A%2F%2Fwww.wikipedia.org%2F

**Comment by dessant** [comment]
Google Cache has been permanently shut down as of 24.09.2024, the cache links no longer work. The search engine will likely be removed from Web Archives in the next release. You can learn more about this topic from the links below.

https://www.seroundtable.com/google-cache-dead-38112.html
https://news.ycombinator.com/item?id=41640845

It is possible that Google has existing contracts with other search engines for displaying Google Cache links next to search results. Yahoo Japan for example used Google Cache in the past, but the search engine is no longer accessible in the EU.  If anyone still manages to access the cache, please share your findings.

**Comment by tapafon** [comment]
Because Google Cache is gone (and no longer accessible in any way), it should be removed from extension.
