### ISSUE TITLE
Clean %3A and %2

### ISSUE THREAD

**Issue by Blackspirits** [dessant/web-archives#94]
https://webcache.googleusercontent.com/search?q=cache:https%3A%2F%2Fwww.netflix.com%2Ftitle%2F81270779

https://webcache.googleusercontent.com/search?q=cache:https://www.netflix.com/title/81270779

Please correct the links, so that they appear with the correct and clean name and do not change to %3A and %2

Thanks

**Comment by dessant** [comment]
The URL should be escaped, otherwise Google Cache may not find the correct resource when certain characters are present.
