### ISSUE TITLE
archive.is is now archive.ph

### ISSUE THREAD

**Issue by Verhagelt** [dessant/web-archives#96]
Archive.is isn't reachable anymore so your link in the add-on also doesn't work. Can you just switch it to archive.ph which is still working ? Thx!

**

**Comment by Verhagelt** [comment]
(using android Firefox)

**Comment by robert-corlett** [comment]
Looks like archive.is is still up -- working on my end.

**Comment by Verhagelt** [comment]
Hmm at least Here in Germany I tried it on several different devices and couldn't reach it. So it might just be nice (if not too complicated) to make it possible for people to choose whether to use .ph/.is/... (Also just in case one of them is down for some hours, happened before..) Thx!!

**Comment by dessant** [comment]
> archive.is is now archive.ph

It's not, both domains are equivalent according to the author and maintainer of the archive service. The customization of the archive.is domain can be followed in this issue: https://github.com/dessant/web-archives/issues/37

You're most likely using Cloudflare DNS if you cannot access Archive.is: https://jarv.is/notes/cloudflare-dns-archive-is-blocked/

**Comment by dessant** [comment]
In Web Archives 7.2.0 you'll be able to change your preferred host for Wayback Machine and Archive.is from the extension's options.
