### ISSUE TITLE
Sci-Hub as a search engine option

### ISSUE THREAD

**Issue by el4ctr0n** [dessant/web-archives#98]
Dear developer,
Can you please add Sci-Hub (https://sci-hub.st/) as a search engine option to this extension?

Thank you for considering my suggestion.

**Comment by dessant** [comment]
Does Sci-Hub or related projects archive some websites too? My impression was that this is not the case, and Web Archives is forcused on finding archived or cached versions of web pages.

**Comment by el4ctr0n** [comment]
> Does Sci-Hub or related projects archive some websites too? My impression was that this is not the case, and Web Archives is focused on finding archived or cached versions of web pages.

Sci-Hub, just like the already included web.archive.org and archive.ph, is used for bypassing paywalls.
